# Generated by Django 5.1.6 on 2025-03-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_fam', models.CharField(max_length=50)),
                ('sharf', models.CharField(max_length=50)),
                ('tel_raqam', models.CharField(blank=True, max_length=13, null=True)),
                ('manzil', models.CharField(max_length=100)),
                ('fan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fan')),
            ],
        ),
    ]
