# Generated by Django 5.1.6 on 2025-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_talaba_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
