# Generated by Django 5.1.6 on 2025-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_talaba_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
