# Generated by Django 5.1.6 on 2025-03-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_talaba_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='fayl',
            field=models.FileField(blank=True, null=True, upload_to='talaba_files/'),
        ),
    ]
